### ISSUE TITLE
UI: Can't choose language Swedish

### ISSUE THREAD

**Issue by maltesk** [varenius/salsa#68]
The language choice menu is sometimes greyed out.

Expect to be able to click on the Language tab and choose Swedish
The language menu is shown in grey and only English is available.
This happens for example when the telescope is tracking.
Workaround: click STOP and then language can be changed.

Tested on Brage 2021-09-01

**Comment by varenius** [comment]
This was considered a feature; when telescope is tracking, some parts of the interface will be locked. So, you write it happens "for example when tracking" but it actually happens "ONLY when tracking". 

So the question is: Do we want to be able to change language while tracking? If so, we can enable this. It should "just work".

**Comment by maltesk** [comment]
Yes please. Changing language is possible during pretty much everything else.

**Comment by varenius** [comment]
Fixed with e11af54
