### ISSUE TITLE
Simple tab: UI doesn't tell me what SALSA is doing now

### ISSUE THREAD

**Issue by maltesk** [varenius/salsa#70]
**Describe the bug**
While using SALSA (Simple tab), I often want to know what the telescope is doing right now (idle, slewing, tracking, measuring, stowed, not available).

**To Reproduce**
Context: Use SALSA for different operations, together with webcam. I try to work out what SALSA is doing while I am using it.
The telescope reports only when it's tracking (in a field marked by "Distance to go"). The two sections "Tracking" and "Measurement" help a bit, but the labels are small and easy to miss.

**Expected behavior**
Expect the UI to show clearly the telescope's current status/activity.

**Desktop (please complete the following information):**
Windows 10, Chrome 95.0.4638.69

**Comment by varenius** [comment]
Implememented TRACKING/SLEWING/IDLE in 4052da8.

**Comment by varenius** [comment]
... although the status is clear only in advanced tab with this commit.

**Comment by varenius** [comment]
Added status field also to simple tab in 02a117e.
