### ISSUE TITLE
Simple tab: STOP button's colour is misleading

### ISSUE THREAD

**Issue by maltesk** [varenius/salsa#73]
**Describe the bug**
While using SALSA, the STOP button in the Simple tab shows in red while the telescope is tracking or slewing. Expect, from the colour, that clicking the STOP button is a dangerous (or perhaps exciting) action. But instead clicking STOP stops the telescope tracking or slewing, neither of which are problematic.

**To Reproduce**
Start SALSA slewing to a new position, so that the number in the "Distance to go" field is changing. The red STOP button is shown.
OR
Move SALSA to a new position so that TRACKING shows. The red STOP button is shown.

**Expected behavior**
Expect any red UI elements to be warnings of some sort of risky outcome (ref: https://uxplanet.org/using-red-and-green-in-ui-design-66b39e13de91).

**Desktop (please complete the following information):**
Windows 10, Chrome 95.0.4638.69

**Comment by varenius** [comment]
I think the red color was picked because you do NOT want to stop the tracking during a measurement. But I can see the problem. Better perhaps to not have a color for the STOP or Stop buttons.
