### ISSUE TITLE
Simple: Wrong figures in Distance to go

### ISSUE THREAD

**Issue by maltesk** [varenius/salsa#76]
**Describe the bug**
The distance to go box sometimes shows the wrong figures.

**To Reproduce**
Enter target and select GO.
Shows TRACKING
Select STOP to stop tracking ready for another target.
"Distance to go" box shows a distance much bigger than zero, which must be wrong.

**Expected behavior**
"Distance to go" box should show something close to zero.

**Desktop (please complete the following information):**
Windows 10, Chrome 97.0.4692.99

**Comment by varenius** [comment]
This is a fun one. I think it has been there all the time, but we just happened to find it now given how the default targets are positioned on the sky. 

SALSA can take two routes to a target. Either with altitude < 90 deg, and go around in az, OR moving less in az but going for  altitude > 90 deg. I suspect that the distance calculator value uses one in the IDLE mode, and another in the tracking mode. Will check this.

**Comment by varenius** [comment]
Should be fixed by 11201bd.
